// ============================================================================
// catalogs-p8.ts — Phase 8 seed data: platform settings, go-live wave
// references, the hypercare support roster and signed schedule, and the gate
// references carried from the owner's approvals (G6 opened the pilot; G7
// approved the awareness materials and authorized the go-live wave plan).
// All rows are DEMONSTRATION data regenerated by the idempotent seed.
// ============================================================================

/** Owner approvals recorded at the gates (decision register references). */
export const G6_APPROVAL_REF = "GATE-G6-2026-09-08"; // signed UAT certificate; migration + pilot authorized
export const G7_APPROVAL_REF = "GATE-G7-2026-09-10"; // pilot exit confirmed; awareness approved; wave plan authorized

export const PLATFORM_SETTINGS_P8 = [
  { key: "auth_mode", value: "demo", note: "Read-path authentication mode; switched to production with the go-live order (DEF-06-01)." },
];

export const AWARENESS_DISTRIBUTION_REF = "DIST-P8-2026-09-POSTER-RADIO-SMS-PORTAL";

export const SUPPORT_ROSTER_P8 = [
  { tier: "WOREDA", role: "Front-desk support (registrars)", assignee: "Alem Tadesse (STF-0001) + woreda desk champions", backup: "Rotating registrar per woreda pair", channel: "Hypercare desk line + on-site round", hours: "08:00-17:30 EAT", escalationLevel: 1 },
  { tier: "WOREDA", role: "Stamping desk support", assignee: "Sara Bekele (STF-0002)", backup: "Sub-city monitor on call", channel: "Hypercare desk line", hours: "08:00-17:30 EAT", escalationLevel: 1 },
  { tier: "SUB_CITY", role: "Sub-city escalation (monitoring, replication)", assignee: "Mulugeta Worku (STF-0003)", backup: "Bureau analyst on call", channel: "Sub-city escalation group", hours: "08:00-20:00 EAT", escalationLevel: 2 },
  { tier: "BUREAU", role: "Bureau escalation (rates, penalties, legal gates)", assignee: "Dawit Kebede (STF-0005)", backup: "Bureau analyst STF-0004", channel: "Bureau operations group", hours: "08:30-17:00 EAT", escalationLevel: 3 },
  { tier: "MINISTRY", role: "Ministry liaison (national feed, policy)", assignee: "Lensa Gemeda (STF-0007)", backup: "Bureau head STF-0005", channel: "Ministry program mailbox", hours: "Business hours", escalationLevel: 4 },
  { tier: "SYSTEM", role: "Platform operations (backups, audit chain, sessions)", assignee: "Kebede Ayele (STF-0008)", backup: "Promotion engineer (on-call rota)", channel: "Ops pager + ops channel", hours: "24/7 on-call during hypercare", escalationLevel: 2 },
];

export const HYPERCARE_PLAN_P8 = {
  waveCode: "WAVE-1",
  days: 28,
  dailyReportTime: "18:00 EAT",
  sla: {
    SEV1: "respond 30 min, workaround 4 h, fix or escalate same day",
    SEV2: "respond 4 h, fix 2 business days",
    SEV3: "respond next business day, fix within the sprint",
    SEV4: "improvement backlog with owner and target",
    daily_report: "18:00 EAT to the owner and tier leads",
    weekly_summary: "Fridays: volumes, SLA adherence, defect movement, training follow-ups",
  },
  signedBy: "Owner's delegate (Gate G7 minute) and the Operations Lead",
  reference: "HC-SCHED-P8-01",
};

export const OPERATIONS_MANUAL_P8 = {
  version: "OPS-MANUAL-v1.0",
  runbookRef: "RUNBOOK-v1.0",
  sections: [
    "Daily operations: front-desk filing, certification and stamping desks; payment ledger reconciliation; deadline sweep",
    "Weekly: replication review (Dir. Art. 13 hops), backup verification, audit-chain verification, hypercare report",
    "Monthly: aggregation snapshots per tier, penalty referral review with competent bodies, Ministry feed",
    "Annual cycle: rate study workspace (March-May), June 1 publication (Proc. Art. 8), June 30 effect, amendment wave and compliance follow-up",
    "Backup and restore: Dir. Art. 13 scheme, FULL/INCREMENTAL runs, count-level restore verification drill",
    "Escalation tree: woreda desk -> sub-city -> Bureau -> Ministry; 24/7 platform pager during hypercare",
    "Access management: staff register, capability matrix, session issuance and revocation (production authentication)",
    "Configuration governance: freeze/hash discipline, per-city configuration sets for replication (Wave 3)",
  ],
};
