// ============================================================================
// catalogs-ops.ts — Phase 8 Part B seed data: operations under the owner's
// go-live order (plan activities A-42..A-48). The Gate G8 decision reference,
// the deterministic hypercare daily-report story, the first annual cycle
// parameters, the enforcement referral register, the Ministry feed schedule,
// the ninety-day PIR findings and the closure-minute content. All rows are
// DEMONSTRATION data regenerated by the idempotent seed.
// ============================================================================

/** Owner Gate G8 decision: the go-live order for Wave 1. */
export const G8_APPROVAL_REF = "GATE-G8-2026-09-10";

/** Annual cycle operated through the real Proc. Art. 8 services (study ->
 *  June 1 publication -> June 30 effect -> amendment wave). The percentage
 *  comes from the Bureau study the record cites. */
export const ANNUAL_CYCLE_2026 = {
  cycleYear: 2026,
  percentage: 8,
  studyRef: "Bureau Annual Rent Study 2026 (plan 5.4 instruments: neighborhood surveys, federal enumeration anchors, 2025 city study)",
};

/** Enforcement referral register (Dir. Art. 22; Proc. Arts. 29-32). Each row
 *  walks the real penalty-case flow (compute -> notify -> refer) and then the
 *  outcome lifecycle. status "OPEN" rows stay in progress deliberately. */
export type EnforcementSeed = {
  offenseCode?: string; subjectType?: string; subjectRef?: string; monthlyRentRef?: number;
  kind: string; subject: string; competentBody: string; basisRef: string; notes?: string;
  outcomes: { status: string; outcomeRef?: string; recovered?: number; notes?: string }[];
};

export const ENFORCEMENT_SEED: EnforcementSeed[] = [
  {
    offenseCode: "PEN-UNAUTH-INCREASE", subjectType: "OVER_CEILING", subjectRef: "AA-BOLE-W01/2026/014",
    monthlyRentRef: 12000, kind: "PENALTY_REFERRAL",
    subject: "Landlord collected above the effected ceiling on a registered Bole W01 contract",
    competentBody: "SUB_CITY", basisRef: "Dir. Art. 22; Proc. Art. 9",
    outcomes: [
      { status: "ACKNOWLEDGED", outcomeRef: "SC-BOLE-ACK-118" },
      { status: "RESOLVED", outcomeRef: "RCPT-PEN-2201", recovered: 24000, notes: "Administrative fine paid; contract rent re-aligned to the ceiling." },
    ],
  },
  {
    offenseCode: "PEN-EXCESS-ADVANCE", subjectType: "OTHER", subjectRef: "AA-BOLE-W02/2026/007",
    monthlyRentRef: 9000, kind: "PENALTY_REFERRAL",
    subject: "Advance payment demanded beyond the two-month cap (Proc. Art. 12)",
    competentBody: "TAX_AUTHORITY", basisRef: "Dir. Art. 22; Proc. Art. 12",
    outcomes: [
      { status: "ACKNOWLEDGED", outcomeRef: "TAX-ACK-2026-334" },
      { status: "RESOLVED", outcomeRef: "TAX-ASSESS-881", recovered: 18000, notes: "Assessed and recovered through the tax administration referral." },
    ],
  },
  {
    offenseCode: "PEN-UNREG-RENT", subjectType: "UNREGISTERED_CONTRACT", subjectRef: "FIELD-VISIT-2026-091",
    monthlyRentRef: 15000, kind: "COURT_RECOVERY",
    subject: "House let without a registered written contract; owner refused woreda summons",
    competentBody: "COURT", basisRef: "Dir. Art. 22; Proc. Art. 4",
    outcomes: [
      { status: "ACKNOWLEDGED", outcomeRef: "CT-ACK-4471" },
      { status: "IN_PROCEEDING", outcomeRef: "CT-DOCKET-2210" },
      { status: "RECOVERY_ORDERED", outcomeRef: "CT-ORDER-2026-118", notes: "Recovery order issued for three months' rent equivalent." },
      { status: "RECOVERED", outcomeRef: "CT-EXEC-2026-118", recovered: 45000, notes: "Full recovery executed; case closed by the court registry." },
      { status: "CLOSED", outcomeRef: "CT-EXEC-2026-118" },
    ],
  },
  {
    offenseCode: "PEN-LATE-REG", subjectType: "UNREGISTERED_CONTRACT", subjectRef: "AA-BOLE-W03/2026/021",
    monthlyRentRef: 8000, kind: "PENALTY_REFERRAL",
    subject: "Registration completed after the grace period; late-registration fine referred",
    competentBody: "BUREAU", basisRef: "Dir. Art. 22; Proc. Art. 4",
    notes: "Left deliberately in progress: demonstrates a live referral with the competent body at closure.",
    outcomes: [
      { status: "ACKNOWLEDGED", outcomeRef: "BUR-ACK-2026-77" },
    ],
  },
];

/** Ministry feed periods: the month `monthOffset` months after the cutover
 *  month (the feed for a period closes at the following month's start). */
export const MINISTRY_FEED_SCHEDULE = [
  { monthOffset: 1, label: "first monthly feed after go-live" },
  { monthOffset: 2, label: "second monthly feed" },
  { monthOffset: 3, label: "third monthly feed, inside the 90-day window" },
];

/** Signed preparation hypercare schedule for Wave 2 (checklist precondition). */
export const HYPERCARE_PLAN_WAVE2 = {
  waveCode: "WAVE-2",
  days: 28,
  dailyReportTime: "18:00 EAT",
  sla: {
    SEV1: "respond 30 min, workaround 4 h, fix or escalate same day",
    SEV2: "respond 4 h, fix 2 business days",
    SEV3: "respond next business day, fix within the sprint",
    SEV4: "improvement backlog with owner and target",
    daily_report: "18:00 EAT to the owner and tier leads",
    weekly_summary: "Fridays: volumes, SLA adherence, defect movement, training follow-ups",
  },
  signedBy: "Operations Lead (Wave 2 preparation pack)",
  reference: "HC-SCHED-P8-02-W2",
};

export const OPERATIONS_HANDOVER_P8B = {
  reference: "HANDOVER-P8-01",
  waveCode: "WAVE-1",
  manualVersion: "OPS-MANUAL-v1.1",
  runbookRef: "RUNBOOK-v1.1",
  signedBy: "Operations Lead Kebede Ayele (STF-0008) and the Owner's delegate (Gate G8 minute)",
  notes: "v1.1 folds hypercare learnings into v1.0: month-end payment surge staffing (BL-01), hosting FD provisioning (DEF-08-01), Wave 2 cutover runbook procedure.",
};

/** Ninety-day PIR findings (plan A-47). */
export const PIR_FINDINGS = [
  { category: "SERVICE", severity: "SEV3", disposition: "BACKLOG", backlogRef: "BL-01",
    description: "Month-end payment surge exceeded level-1 support staffing; the day-9 SEV-3 response missed its next-business-day target. Backlog: cross-train sub-city support for month-end cover." },
  { category: "OPERATIONS", severity: "SEV4", disposition: "HANDOVER",
    description: "Sandbox file-descriptor ceiling encountered during load rehearsal (DEF-08-01) is a hosting-provisioning item; documented in operations manual v1.1 hosting section for the production estate." },
  { category: "TRAINING", severity: "OPPORTUNITY", disposition: "BACKLOG", backlogRef: "BL-02",
    description: "Competency decay observed around day 60 at one woreda desk; backlog: registrar refresher round before the Wave 2 rotation." },
  { category: "LEGAL", severity: "SEV4", disposition: "ACCEPTED",
    description: "Open item O-1 (official Amharic fine-ladder figures) remains with the directive issuer; configurable PEN-* parameters carry PENDING_OFFICIAL_TEXT and the engine reads parameters, so the update is a data change. Residual risk accepted at closure." },
  { category: "SERVICE", severity: "OPPORTUNITY", disposition: "BACKLOG", backlogRef: "BL-03",
    description: "Woreda desks requested SMS receipt notifications to parties after payment recording; recorded as an enhancement opportunity in the backlog." },
  { category: "OPERATIONS", severity: "SEV4", disposition: "HANDOVER",
    description: "Wave 2 (city-wide) cutover order pending with city operations; sequencing gates satisfied (Wave 1 live, O-7 closed, checklist green) and the wave procedure is in runbook v1.1." },
];

/** Closure minute content (plan A-48) — lessons, BAU transitions, final
 *  open-item register. Signature is reserved for the owner's Gate G9 decision. */
export const CLOSURE_MINUTE_P8B = {
  reference: "CM-P8-G9-01",
  lessons: [
    "Migration succeeded because the register was treated as the contract: Dir. Art. 8(2) legacy annotation kept the paper truth while the platform reconciled to it woreda by woreda, and unscanned rows were refused rather than approximated.",
    "Role- and tier-based training paid for itself in hypercare: no severity-one incident traced to front-desk operation, and desk champions absorbed the bulk of tickets at level 1.",
    "Legal gates encoded in software (checklist, two-year term, ceiling, electronic payment) behaved as law rather than as features; officers learned the rules through the platform's refusals, each carrying the article it protects.",
    "Evidence discipline — append-only registers, hash-verified feeds, immutable reconciliation reports — kept gate reviews short because every fact was re-readable live in three languages.",
    "The compressed demonstrator schedule stayed honest by recording the full operational arc with explicit bases and dates rather than claiming wall-clock realism; every seed row cites its plan activity and legal basis.",
    "Escalation levels 2-4 stayed cool because level 1 (woreda desk champions) was staffed and trained first; support structure followed the administrative tiers of the Directive.",
  ],
  transitions: [
    "Wave 2 (city-wide, remaining 10 sub-cities): checklist green and sequencing gates satisfied; the cutover order rests with city operations under runbook v1.1 wave procedure.",
    "Authentication: production read-path mode armed and drilled; the switch is thrown at each physical cutover per runbook section 'Access management' (DEF-06-01 closure discipline).",
    "O-1 (official Amharic fine-ladder figures): configurable PEN-* parameters; the official text lands as a data update without code change.",
    "O-8 (certified Afan Oromo legal glossary): CR-01 fallback active; terminology workshop scheduled with the culture bureau as a BAU activity.",
    "Improvement backlog BL-01..BL-03 transfers to operations with a monthly review; the PIR register carries the dispositions.",
    "Ministry feed continues monthly under runbook v1.1; periods are immutable and hash-verified.",
  ],
  openItems: [
    "O-1: CLOSED_BY_DISPOSITION — configurable penalty parameters await the official figures; engine reads parameters, never constants.",
    "O-8: HANDOVER — certified glossary workshop with the culture bureau; trilingual fallback active (CR-01/NFR-06).",
    "DEF-08-01: CLOSED — hosting FD provisioning documented in operations manual v1.1.",
    "Defect register: no open defects at any severity at closure (DEF-06-01..03, DEF-07-01..02, DEF-08-01..02 all closed).",
  ],
};
