// ============================================================================
// catalogs-p7.ts — Phase 7 seed data: legacy registry books of the pilot
// woredas (Proc. Art. 7; Dir. Art. 8(2)), the role-and-tier training
// curriculum, the pilot configuration with its day logs, and the trilingual
// awareness materials awaiting the owner's Gate G7 approval.
// All rows are DEMONSTRATION data for the pilot scope and are regenerated by
// the idempotent seed (prisma/seed.ts).
// ============================================================================

export interface LegacyEntrySpec {
  pageNo: number;
  entryNo: number;
  landlordName: string;
  tenantName: string;
  houseAddress: string;
  monthlyRent: number;
  contractDate: string; // ISO
  leaseStart: string;
  leaseYears: number;
}

// Book references follow the Dir. Art. 9 registry book format of the woreda.
export const PILOT_WOREDA_CODES = ["AA-BOLE-W01", "AA-BOLE-W02", "AA-BOLE-W03"];

export const LEGACY_BOOKS: Record<string, { bookRef: string; entries: LegacyEntrySpec[] }> = {
  "AA-BOLE-W01": {
    bookRef: "BL-W1-RB-03",
    entries: [
      { pageNo: 1, entryNo: 1, landlordName: "Ato Bekele Wolde", tenantName: "W/ro Selamawit Girma", houseAddress: "Keble 03, House 214, Bole W01", monthlyRent: 12000, contractDate: "2022-03-15", leaseStart: "2022-04-01", leaseYears: 3 },
      { pageNo: 1, entryNo: 2, landlordName: "W/ro Tigist Alemu", tenantName: "Ato Yonas Kebede", houseAddress: "Keble 04, House 88, Bole W01", monthlyRent: 9500, contractDate: "2022-06-02", leaseStart: "2022-07-01", leaseYears: 2 },
      { pageNo: 1, entryNo: 3, landlordName: "Ato Mulugeta Tesfaye", tenantName: "W/ro Hanna Solomon", houseAddress: "Keble 05, House 12, Bole W01", monthlyRent: 15000, contractDate: "2023-01-20", leaseStart: "2023-02-01", leaseYears: 3 },
      { pageNo: 1, entryNo: 4, landlordName: "Ato Dereje Bekele", tenantName: "Ato Samuel Negash", houseAddress: "Keble 03, House 310, Bole W01", monthlyRent: 8000, contractDate: "2021-11-11", leaseStart: "2021-12-01", leaseYears: 2 },
      { pageNo: 1, entryNo: 5, landlordName: "W/ro Almaz Haile", tenantName: "Ato Fikru Mengistu", houseAddress: "Keble 07, House 45, Bole W01", monthlyRent: 11000, contractDate: "2022-09-05", leaseStart: "2022-10-01", leaseYears: 3 },
      { pageNo: 2, entryNo: 6, landlordName: "Ato Getachew Molla", tenantName: "W/ro Marta Ayele", houseAddress: "Keble 08, House 156, Bole W01", monthlyRent: 13500, contractDate: "2023-04-18", leaseStart: "2023-05-01", leaseYears: 2 },
      { pageNo: 2, entryNo: 7, landlordName: "W/ro Roman Tadesse", tenantName: "Ato Dawit Girma", houseAddress: "Keble 09, House 77, Bole W01", monthlyRent: 10000, contractDate: "2023-08-30", leaseStart: "2023-09-15", leaseYears: 2 },
      { pageNo: 2, entryNo: 8, landlordName: "Ato Solomon Worku", tenantName: "W/ro Hiwot Berhanu", houseAddress: "Keble 10, House 23, Bole W01", monthlyRent: 12500, contractDate: "2021-05-25", leaseStart: "2021-06-10", leaseYears: 3 },
      { pageNo: 2, entryNo: 9, landlordName: "W/ro Genet Assefa", tenantName: "Ato Bereket Tessema", houseAddress: "Keble 11, House 190, Bole W01", monthlyRent: 9000, contractDate: "2022-12-08", leaseStart: "2023-01-01", leaseYears: 2 },
      { pageNo: 2, entryNo: 10, landlordName: "Ato Tesfaye Abebe", tenantName: "W/ro Rahel Mekonnen", houseAddress: "Keble 12, House 61, Bole W01", monthlyRent: 14000, contractDate: "2023-02-14", leaseStart: "2023-03-01", leaseYears: 3 },
      { pageNo: 3, entryNo: 11, landlordName: "Ato Ibrahim Nur", tenantName: "Ato Kedir Jemal", houseAddress: "Keble 13, House 34, Bole W01", monthlyRent: 8500, contractDate: "2022-04-22", leaseStart: "2022-05-05", leaseYears: 2 },
      { pageNo: 3, entryNo: 12, landlordName: "W/ro Zewditu Kebede", tenantName: "Ato Nigussie Tesfaye", houseAddress: "Keble 14, House 102, Bole W01", monthlyRent: 11500, contractDate: "2023-06-19", leaseStart: "2023-07-01", leaseYears: 2 },
    ],
  },
  "AA-BOLE-W02": {
    bookRef: "BL-W2-RB-02",
    entries: [
      { pageNo: 1, entryNo: 1, landlordName: "Ato Ayalew Biru", tenantName: "W/ro Eden Haile", houseAddress: "Keble 01, House 55, Bole W02", monthlyRent: 10500, contractDate: "2022-02-10", leaseStart: "2022-03-01", leaseYears: 2 },
      { pageNo: 1, entryNo: 2, landlordName: "W/ro Askalu Menberu", tenantName: "Ato Girum Seifu", houseAddress: "Keble 02, House 240, Bole W02", monthlyRent: 13000, contractDate: "2023-01-05", leaseStart: "2023-02-01", leaseYears: 3 },
      { pageNo: 1, entryNo: 3, landlordName: "Ato Hagos Gebre", tenantName: "W/ro Lidya Abebe", houseAddress: "Keble 03, House 19, Bole W02", monthlyRent: 9800, contractDate: "2021-09-30", leaseStart: "2021-10-15", leaseYears: 2 },
      { pageNo: 1, entryNo: 4, landlordName: "Ato Wondimu Gossa", tenantName: "Ato Henok Alemayehu", houseAddress: "Keble 05, House 71, Bole W02", monthlyRent: 12200, contractDate: "2022-08-12", leaseStart: "2022-09-01", leaseYears: 2 },
      { pageNo: 1, entryNo: 5, landlordName: "W/ro Mestawat Jemberu", tenantName: "Ato Tewodros Kasahun", houseAddress: "Keble 06, House 133, Bole W02", monthlyRent: 8800, contractDate: "2023-03-27", leaseStart: "2023-04-10", leaseYears: 2 },
      { pageNo: 2, entryNo: 6, landlordName: "Ato Kassa Wolde", tenantName: "W/ro Sosina Mitiku", houseAddress: "Keble 07, House 8, Bole W02", monthlyRent: 14200, contractDate: "2023-05-16", leaseStart: "2023-06-01", leaseYears: 3 },
      { pageNo: 2, entryNo: 7, landlordName: "W/ro Belaynesh Fikadu", tenantName: "Ato Endalkachew Wube", houseAddress: "Keble 08, House 210, Bole W02", monthlyRent: 10900, contractDate: "2022-10-03", leaseStart: "2022-11-01", leaseYears: 2 },
      { pageNo: 2, entryNo: 8, landlordName: "Ato Gemechu Dinka", tenantName: "Ato Biniyam Tolosa", houseAddress: "Keble 09, House 46, Bole W02", monthlyRent: 9200, contractDate: "2023-07-21", leaseStart: "2023-08-05", leaseYears: 2 },
      { pageNo: 2, entryNo: 9, landlordName: "W/ro Frehiwot Admasu", tenantName: "W/ro Tsehay Bezuayehu", houseAddress: "Keble 10, House 118, Bole W02", monthlyRent: 11800, contractDate: "2022-01-17", leaseStart: "2022-02-01", leaseYears: 3 },
    ],
  },
  "AA-BOLE-W03": {
    bookRef: "BL-W3-RB-01",
    entries: [
      { pageNo: 1, entryNo: 1, landlordName: "Ato Tefera Desta", tenantName: "Ato Mekdes Fikre", houseAddress: "Keble 02, House 90, Bole W03", monthlyRent: 13200, contractDate: "2022-05-28", leaseStart: "2022-06-15", leaseYears: 3 },
      { pageNo: 1, entryNo: 2, landlordName: "W/ro Yeshi Alemayehu", tenantName: "Ato Robel Girmay", houseAddress: "Keble 03, House 12, Bole W03", monthlyRent: 8900, contractDate: "2023-02-09", leaseStart: "2023-03-01", leaseYears: 2 },
      { pageNo: 1, entryNo: 3, landlordName: "Ato Alemu Sisay", tenantName: "W/ro Betty Hagos", houseAddress: "Keble 04, House 200, Bole W03", monthlyRent: 10800, contractDate: "2021-12-20", leaseStart: "2022-01-10", leaseYears: 2 },
      { pageNo: 1, entryNo: 4, landlordName: "W/ro Konjit Moges", tenantName: "Ato Natnael Zerihun", houseAddress: "Keble 06, House 58, Bole W03", monthlyRent: 12600, contractDate: "2023-04-03", leaseStart: "2023-04-20", leaseYears: 3 },
      { pageNo: 1, entryNo: 5, landlordName: "Ato Shiferaw Guta", tenantName: "Ato Emnet Wondwosen", houseAddress: "Keble 07, House 141, Bole W03", monthlyRent: 9600, contractDate: "2022-07-14", leaseStart: "2022-08-01", leaseYears: 2 },
      { pageNo: 2, entryNo: 6, landlordName: "W/ro Hirut Mequanint", tenantName: "Ato Yosef Mamo", houseAddress: "Keble 08, House 33, Bole W03", monthlyRent: 13900, contractDate: "2023-09-08", leaseStart: "2023-10-01", leaseYears: 2 },
      { pageNo: 2, entryNo: 7, landlordName: "Ato Fisseha Yohannes", tenantName: "W/ro Meron Tafere", houseAddress: "Keble 09, House 175, Bole W03", monthlyRent: 8700, contractDate: "2022-11-26", leaseStart: "2022-12-10", leaseYears: 2 },
    ],
  },
};

export const TOTAL_LEGACY_ROWS = Object.values(LEGACY_BOOKS)
  .reduce((s, b) => s + b.entries.length, 0); // 28

// ---------------------------------------------------------------------------
// Training curriculum (plan section 5.8: registrar front-desk practice,
// sub-city monitoring, Bureau analytics and rate publication, administration)
// ---------------------------------------------------------------------------
export const TRAINING_COURSES = [
  {
    code: "TRN-W1",
    titleEn: "Woreda Registrar Front-Desk Practice",
    titleAm: "የወረዳ መመዝጊ የግንባታ ጠረጴዛ ተልቋ ልምምድ",
    titleOm: "Shuguddaa Galmeessaa Woredaa Adda Cinaa",
    tierScope: "WOREDA", audienceRole: "WOREDA_REGISTRAR",
    modules: "Intake and original-and-copy rule; nine-point checklist; certification; registry book; deadline register; complaint intake",
    durationHours: 12, legalBasis: "Dir. Arts. 6-9, 17-19; Proc. Arts. 4, 20",
  },
  {
    code: "TRN-W2",
    titleEn: "Stamping Desk Practice",
    titleAm: "የማህተም ጠረጴዛ ተልቋ ልምምድ",
    titleOm: "Shuguddaa Warqeeffamaa",
    tierScope: "WOREDA", audienceRole: "WOREDA_STAMPER",
    modules: "Round stamp and back-stamp annotation; separation of duties; certificate numbering; desk audit trail",
    durationHours: 6, legalBasis: "Dir. Arts. 9-10",
  },
  {
    code: "TRN-S1",
    titleEn: "Sub-City Monitoring and Replication",
    titleAm: "የክፍለ ከተማ ክትትል እና መቀላቀል",
    titleOm: "Itiinsa fi Wal-qunnamtii Kutaa Magaalaa",
    tierScope: "SUB_CITY", audienceRole: "SUBCITY_MONITOR",
    modules: "Aggregation dashboards; replication runs; control visits; vacancy monitoring; escalation to Bureau",
    durationHours: 8, legalBasis: "Dir. Arts. 13, 20; Proc. Art. 20",
  },
  {
    code: "TRN-B1",
    titleEn: "Bureau Analytics and Rate Publication",
    titleAm: "የቢሮ ትንተና እና የዋጋ ማስታወቂያ",
    titleOm: "Qorannoo fi Beeksisa Kallattii Biroo",
    tierScope: "BUREAU", audienceRole: "BUREAU_ANALYST",
    modules: "Market study workspace; adjustment drafting; June 1 publication; June 30 effect; ceiling queries; national reporting",
    durationHours: 10, legalBasis: "Proc. Arts. 8-9; Dir. Arts. 11, 13",
  },
  {
    code: "TRN-B2",
    titleEn: "Bureau Head Decisions and Penalties",
    titleAm: "የቢሮ ኃላፊ ውሳኔዎች እና ቅጣቶች",
    titleOm: "Murtiitii Adabbii Ijoollee Biroo",
    tierScope: "BUREAU", audienceRole: "BUREAU_HEAD",
    modules: "Adjustment publication and effect authority; penalty ladder; notifications and referrals; fine cap; legal session duties",
    durationHours: 8, legalBasis: "Proc. Arts. 8, 29-32; Dir. Art. 22",
  },
  {
    code: "TRN-S9",
    titleEn: "System Administration and Continuity",
    titleAm: "የስርዓት አስተዳደር እና ቀጣይነት",
    titleOm: "Bulchiinsa Sirna fi Itti fufiinsa",
    tierScope: "SYSTEM", audienceRole: "SYSTEM_ADMIN",
    modules: "Staff register; backups and restore drill; staged promotion; audit chain verification; deadline sweep; UAT coordination",
    durationHours: 10, legalBasis: "Dir. Arts. 14, 16; NFR-04/07",
  },
];

// Training sessions already held during the pilot window, with competence
// records for the demo staff (all roles covered -> pilot exit check passes).
export const TRAINING_SESSIONS = [
  { courseCode: "TRN-W1", trainer: "Lead Registrar Trainer", orgCode: "AA-BOLE-W01", venue: "Bole W01 training room", daysAgo: 12, trainees: [
    { name: "Abebe Kebede (role designation)", staffCode: "STF-0001", roleCode: "WOREDA_REGISTRAR", attendance: "PRESENT", score: 92 },
    { name: "Selam Tadesse", staffCode: null, roleCode: "WOREDA_REGISTRAR", attendance: "PRESENT", score: 84 },
  ]},
  { courseCode: "TRN-W2", trainer: "Registry Practice Trainer", orgCode: "AA-BOLE-W01", venue: "Bole W01 training room", daysAgo: 11, trainees: [
    { name: "Marta Hailu (role designation)", staffCode: "STF-0002", roleCode: "WOREDA_STAMPER", attendance: "PRESENT", score: 88 },
  ]},
  { courseCode: "TRN-S1", trainer: "Sub-City Operations Trainer", orgCode: "AA-BOLE", venue: "Bole sub-city hall", daysAgo: 10, trainees: [
    { name: "Yohannes Girma (role designation)", staffCode: "STF-0003", roleCode: "SUBCITY_MONITOR", attendance: "PRESENT", score: 86 },
    { name: "Hana Mekonnen", staffCode: null, roleCode: "SUBCITY_MONITOR", attendance: "PRESENT", score: 61 },
  ]},
  { courseCode: "TRN-B1", trainer: "Bureau Study Lead", orgCode: "AA-BUREAU", venue: "Bureau conference room", daysAgo: 11, trainees: [
    { name: "Lidya Fikru (role designation)", staffCode: "STF-0004", roleCode: "BUREAU_ANALYST", attendance: "PRESENT", score: 90 },
  ]},
  { courseCode: "TRN-B2", trainer: "Legal Session Chair", orgCode: "AA-BUREAU", venue: "Bureau conference room", daysAgo: 10, trainees: [
    { name: "Dawit Kebede (role designation)", staffCode: "STF-0005", roleCode: "BUREAU_HEAD", attendance: "PRESENT", score: 94 },
  ]},
  { courseCode: "TRN-S9", trainer: "Platform Engineering", orgCode: "AA-BUREAU", venue: "Bureau IT room", daysAgo: 9, trainees: [
    { name: "System Administrator (role designation)", staffCode: "STF-0008", roleCode: "SYSTEM_ADMIN", attendance: "PRESENT", score: 91 },
  ]},
  // Committee member refresher attached to the appeal workflow.
  { courseCode: "TRN-S1", trainer: "Committee Secretariat", orgCode: "AA-BUREAU", venue: "Bureau hearing room", daysAgo: 8, trainees: [
    { name: "Committee Member (role designation)", staffCode: "STF-0006", roleCode: "COMMITTEE_MEMBER", attendance: "PRESENT", score: 87 },
  ]},
];

// ---------------------------------------------------------------------------
// Pilot configuration and day logs (plan section 5.8 measurement set:
// registration cycle time, checklist compliance, replication correctness)
// ---------------------------------------------------------------------------
export const PILOT_SPEC = {
  subCityCode: "AA-BOLE",
  woredaCodes: PILOT_WOREDA_CODES,
  plannedWeeks: 2,
  ownerApprovalRef: "G6-APPROVAL-2026-09",
  daysAgoStart: 9,
  // Two working weeks of day logs across the three woredas (weekends skipped
  // by the generator). Cycle time falls as practice settles; compliance rises.
  daysPerWoreda: 6,
};

// ---------------------------------------------------------------------------
// Awareness materials (Proc. Arts. 14, 16) — trilingual; the owner approves
// them at Gate G7.
// ---------------------------------------------------------------------------
export const AWARENESS_ITEMS = [
  {
    basis: "Proc. Art. 16", channel: "POSTER",
    titleEn: "What a valid rent contract looks like",
    titleAm: "ትክክለኛ የኪራይ ውል እንዴት ይመስላል",
    titleOm: "Waliin kiraalaa dhugaa akkam fakkaata",
    bodyEn: "A valid residential rent contract is written on the Bureau model contract, certified at your woreda, carries the office stamp, and is registered in the woreda registry book within 30 days. Keep your certified copy - it is your legal protection.",
  },
  {
    basis: "Proc. Art. 14", channel: "RADIO",
    titleEn: "Know your rights and duties under the rent proclamation",
    titleAm: "በኪራይ አዋጁ መብቶችንና ግዴታዎችዎን ይወቁ",
    titleOm: "Mirga fi dirqama kee kiraalaa beekuu",
    bodyEn: "Rent is paid only through electronic channels; the advance cannot exceed two months; increases follow the published ceiling; disputes go to your woreda office first. Listen for the Bureau's weekly program on your local station.",
  },
  {
    basis: "Proc. Art. 14", channel: "SMS",
    titleEn: "Legacy contracts: register before the deadline",
    titleAm: "ቀደም ያሉ ውሎች፦ ከጊዜው በፊት ያስመዝግቡ",
    titleOm: "Waliin duraa: guyyaa dura galmeessi",
    bodyEn: "Existing rent contracts must be presented at the woreda where the house is located within 30 days plus 3 grace days of the announcement. Registration protects both landlord and tenant.",
  },
  {
    basis: "Proc. Art. 16", channel: "PORTAL",
    titleEn: "The annual rent ceiling, explained",
    titleAm: "ዓመታዊ የኪራይ ጣሪያ ያስረዳ",
    titleOm: "Daangaa kiraalaa waggaaati ifa jecha",
    bodyEn: "Each June 1 the Bureau publishes the maximum increase; from June 30 the new ceiling applies. Check the ceiling for your woreda on this portal before signing or renewing any contract.",
  },
];
