// plan_content_d.js — Chapters 10-12
const { h1, h2, h3, p, rich, bullet, tbl } = require("./plan_lib");

function chapter10() {
  return [
    h1("10. Timeline, Milestones and Risk Register"),
    h2("10.1 Indicative Schedule"),
    p("The durations below are planning estimates to be fixed at Gate G0 once staffing and office availability are known. They are included so that the sequence and relative weight of phases are visible now. No duration here is a commitment; the schedule baseline produced in Phase 0 is the commitment."),
    ...tbl({
      caption: "Indicative phase schedule",
      headers: ["Phase", "Indicative duration", "Milestone at exit"],
      widths: [30, 22, 48],
      zebra: true,
      rows: [
        ["Phase 0 Initiation", "2 weeks", "M0: charter and plan approved"],
        ["Phase 1 Requirements", "4 weeks", "M1: SRS and traceability approved"],
        ["Phase 2 Design", "4 weeks", "M2: architecture and designs approved"],
        ["Phase 3 Environments", "2 weeks", "M3: pipelines and seeded configuration live"],
        ["Phase 4 Construction", "10 to 14 weeks (7 sprints)", "M4: functionally complete platform demonstrated"],
        ["Phase 5 Testing", "4 weeks", "M5: compliance and security evidence accepted"],
        ["Phase 6 UAT and legal validation", "3 weeks", "M6: UAT certificate signed"],
        ["Phase 7 Migration and pilot", "6 weeks", "M7: pilot exit approved"],
        ["Phase 8 Go-live and operations", "Rolling waves; hypercare 4 weeks; review at 90 days", "M8 go-live; M9 project closure"],
      ],
    }),
    h2("10.2 Risk Register"),
    p("Risks are managed openly: each has an owner, a mitigation already built into the plan, and a review at every gate. The register below holds the ten risks judged most consequential at this stage; Phase 0 extends it with likelihood and impact scoring agreed with the stakeholders."),
    ...tbl({
      caption: "Risk register (top ten)",
      headers: ["Risk", "Likelihood", "Impact", "Mitigation built into this plan"],
      widths: [30, 12, 12, 46],
      zebra: true,
      rows: [
        ["Legal parameter ambiguity (fine ladder, dates) misread from scanned text", "Medium", "High", "Phase 1 verification against official texts; parameters configurable, not coded; decision register records each value"],
        ["Low digital familiarity at some woreda offices", "Medium", "High", "Role-based hands-on training; pilot wave before city-wide rollout; registrar workbench mirrors paper checklist"],
        ["Connectivity or power interruptions at woreda level", "Medium", "Medium", "Offline-tolerant workbench design considered in Phase 2; tier-level backups per Directive Art. 13"],
        ["Bank and electronic payment integration delays", "Medium", "High", "Early sandbox engagement in Phase 3; payment ledger isolated behind interfaces; fallback manual reconciliation flagged for audit"],
        ["Legacy registry data quality poor or incomplete", "High", "Medium", "Migration with reconciliation counts; discrepancy log; dual running until balanced"],
        ["Resistance from parts of the landlord community", "Medium", "Medium", "Public awareness duty executed per Arts. 14 and 16; incentives for lawful landlords surfaced in the platform"],
        ["Scope creep from well-meant additions", "Medium", "Medium", "Change control with one-page impact assessment; decision register; gate approvals"],
        ["Single-team or single-vendor dependence", "Low", "High", "Full documentation set as gate deliverables; configuration over code; handover operations manual"],
        ["Security breach or data exposure", "Low", "High", "OWASP ASVS testing; tier-scoped access; encryption; immutable audit log; incident runbook"],
        ["Pilot woreda unrepresentative, giving false confidence", "Medium", "Medium", "Pilot selection at G7 includes at least one high-volume and one low-volume woreda"],
      ],
    }),
  ];
}

function chapter11() {
  return [
    h1("11. Master Activity Checklist"),
    p("This checklist is the single list to follow. It consolidates every activity from the phases, gates, testing, migration and rollout discussions into one numbered sequence, so that nothing agreed in this engagement can be lost. Each activity names its phase and its concrete output; the output is what the gate reviews."),
    ...tbl({
      caption: "Master activity checklist",
      headers: ["ID", "Activity", "Phase", "Output"],
      widths: [9, 51, 12, 28],
      zebra: true,
      rows: [
        ["A-01", "Confirm the three legal instruments as binding baseline and obtain official Amharic texts", "P0", "Baseline confirmation note"],
        ["A-02", "Appoint project owner, product owner and tier stakeholders", "P0", "Stakeholder map"],
        ["A-03", "Approve implementation plan and project charter", "P0", "Signed charter, this plan v1.0"],
        ["A-04", "Stand up workspace, repositories and decision register", "P0", "Collaboration environment"],
        ["A-05", "Reconcile proclamation, directive and model agreement into one requirement set", "P1", "Requirement set v1.0"],
        ["A-06", "Resolve flagged ambiguities, especially Directive Art. 22 fine ladder", "P1", "Resolved-parameter log"],
        ["A-07", "Build bilingual EN and Amharic terminology glossary", "P1", "Glossary"],
        ["A-08", "Write SRS to ISO/IEC/IEEE 29148 with unique identifiers", "P1", "SRS v1.0"],
        ["A-09", "Build article-requirement-module-use case-test traceability matrix", "P1", "Traceability matrix v1.0"],
        ["A-10", "Design high-level architecture for public portal, registrar workbench, tier consoles and Ministry analytics", "P2", "Architecture specification"],
        ["A-11", "Design database schema across parties to audit log", "P2", "Database design"],
        ["A-12", "Design security: tier-scoped RBAC, encryption, immutable audit", "P2", "Security and threat model"],
        ["A-13", "Design bilingual interfaces against model contract fields and checklist screens", "P2", "Wireframe pack"],
        ["A-14", "Specify integration services: bank and e-payment, identification, notifications", "P2", "Interface specification"],
        ["A-15", "Provision development, staging and production environments with tier backups", "P3", "Environment inventory"],
        ["A-16", "Build CI/CD pipelines with staged promotion and release tagging", "P3", "Pipeline documentation"],
        ["A-17", "Seed configuration: hierarchy, roles, identification catalogues, statuses, model contract v1, penalty ladder, June calendar", "P3", "Seeded configuration"],
        ["A-18", "Sprint 1: build organization hierarchy, roles and party onboarding", "P4", "Increment 1 demo"],
        ["A-19", "Sprint 2: build property registry with status and exemption clocks; model contract studio", "P4", "Increment 2 demo"],
        ["A-20", "Sprint 3: build registration and certification workflow with checklist, interpreter flow, stamping, numbering, legacy annotation", "P4", "Increment 3 demo"],
        ["A-21", "Sprint 4: build adjustment engine with June calendar; payment ledger with cash flagging", "P4", "Increment 4 demo"],
        ["A-22", "Sprint 5: build complaint intake, dispute pipeline and deadline engine", "P4", "Increment 5 demo"],
        ["A-23", "Sprint 6: build control teams, vacancy monitoring, penalty ladder, referrals and court tracking", "P4", "Increment 6 demo"],
        ["A-24", "Sprint 7: build replication, backup, dashboards, aggregation and publication feed", "P4", "Increment 7 demo; functional completeness"],
        ["A-25", "Run integration tests with bank sandbox and identification service including failure paths", "P5", "Integration report"],
        ["A-26", "Run system and regression testing against use cases", "P5", "System test report"],
        ["A-27", "Run performance tests at woreda and city-scale loads", "P5", "Performance report"],
        ["A-28", "Run security testing to the agreed OWASP ASVS level", "P5", "Security assessment"],
        ["A-29", "Execute the legal compliance test matrix for every traced article", "P5", "Compliance matrix with results"],
        ["A-30", "Prepare UAT scripts from the twenty-one use cases", "P6", "UAT script pack"],
        ["A-31", "Run role-based UAT with nominated role players", "P6", "UAT results"],
        ["A-32", "Hold legal validation walkthrough of the compliance matrix with Bureau experts", "P6", "Legal validation memorandum"],
        ["A-33", "Triage and fix UAT defects; re-test with evidence", "P6", "Closed defect log"],
        ["A-34", "Obtain signed UAT certificate", "P6", "UAT certificate"],
        ["A-35", "Migrate legacy contracts with Article 8(2) annotation and four-witness data", "P7", "Migration dataset"],
        ["A-36", "Scan and attach legacy documents; reconcile against registry books", "P7", "Reconciliation report"],
        ["A-37", "Deliver role-based training across woreda, sub-city, Bureau and IT", "P7", "Training records"],
        ["A-38", "Prepare public awareness materials per Arts. 14 and 16", "P7", "Awareness pack"],
        ["A-39", "Operate pilot woredas with daily support and measures", "P7", "Pilot exit report"],
        ["A-40", "Select go-live waves and confirm readiness at G7", "P7", "Wave plan"],
        ["A-41", "Execute cutover checklist and give go-live order", "P8", "Go-live record"],
        ["A-42", "Run hypercare support with daily reporting", "P8", "Hypercare reports"],
        ["A-43", "Operate the annual adjustment cycle: study, June 1 publication, June 30 effect, amendment wave", "P8", "First-cycle operation record"],
        ["A-44", "Operate penalty referrals and court-recovery tracking with competent bodies", "P8", "Referral and recovery records"],
        ["A-45", "Publish national data to the Ministry feed", "P8", "Publication record"],
        ["A-46", "Hand over operations manual and runbook; close hypercare", "P8", "Signed handover"],
        ["A-47", "Conduct ninety-day post-implementation review", "P8", "PIR report and backlog"],
        ["A-48", "Close project at Gate G9 with lessons recorded", "P8", "Closure minute"],
      ],
    }),
  ];
}

function chapter12() {
  return [
    h1("12. Appendix A: Legal Traceability Matrix and Glossary"),
    h2("12.1 Traceability Matrix (Summary View)"),
    p("The full matrix lives with the SRS and is maintained from Phase 1 onward; the summary below shows the mapping pattern by article range so that coverage of the law is visible at a glance. Every row of the full matrix carries the requirement identifier, the design element, and the test case that proves it."),
    ...tbl({
      caption: "Legal source to module mapping",
      headers: ["Legal source", "Articles", "Modules", "Requirement group"],
      widths: [26, 18, 22, 34],
      zebra: true,
      rows: [
        ["Scope and definitions", "Proc. Art. 2, 3", "M2, M13", "Scope engine, status classification, exclusions"],
        ["Contract form, registration, validity", "Proc. Art. 4, 5; Dir. Art. 4 to 9", "M3, M4", "Contract studio, registration and certification workflow"],
        ["Term, renewal, legacy migration", "Proc. Art. 6, 7; Dir. Art. 10", "M3, M4, M12", "Term rules, amendments, thirty-day windows"],
        ["Price control and adjustment", "Proc. Art. 8 to 11; Dir. Art. 11", "M5", "Ceiling computation, June calendar, increase validation"],
        ["Exemptions and incentives", "Proc. Art. 9, 10", "M2, M5", "Exemption clocks, false-information guard"],
        ["Payment discipline", "Proc. Art. 12 to 14; Dir. Art. 16(4)", "M6", "Electronic ledger, cash flagging, evidentiary pairing"],
        ["Institutions and duties", "Proc. Art. 18, 19; Dir. Art. 14 to 16", "M11, M13", "Tier consoles, aggregation, configuration"],
        ["Complaints, appeals, decisions", "Proc. Art. 20 to 26; Dir. Art. 17 to 19", "M8, M12", "Intake, investigation, committee appeal, court clock"],
        ["Control and enforcement", "Proc. Art. 20; Dir. Art. 20 to 22", "M7, M9", "Team control, vacancy bands, referrals, recovery"],
        ["Data custody and security", "Dir. Art. 12, 13", "M10", "Corrections, scanning, replication, backup"],
      ],
    }),
    h2("12.2 Glossary"),
    ...tbl({
      caption: "Key terms",
      headers: ["Term", "Meaning in this project"],
      widths: [30, 70],
      zebra: true,
      rows: [
        ["Akeray (landlord)", "The party that lets a residential house; onboarding actor of module M1"],
        ["Tekeray (tenant)", "The party that rents a residential house; payer in the electronic ledger"],
        ["Proclamation", "Residential House Rent Control and Administration Proclamation No. 1320/2016"],
        ["Directive", "Addis Ababa City Directive No. 7/2016 issued under Proclamation Article 29(2)"],
        ["Model agreement", "The standard rental contract annexed to the directive and digitized in module M3"],
        ["Bureau", "The city Housing Development and Administration Bureau; the Regulatory Body head for Addis Ababa"],
        ["Sub-city office", "The intermediate housing office that aggregates woreda data and monitors implementation"],
        ["Woreda office", "The registration front desk: verification, certification, stamping, complaints, penalties"],
        ["Registry book", "The uniform numbered hard-copy register kept in every woreda alongside the database"],
        ["Regulatory Body", "Collectively, the Bureau and the offices empowered to control rent contracts and prices"],
        ["Legacy contract", "A rental contract concluded before the proclamation took effect, registered with the Article 8(2) annotation"],
        ["Adjustment rate", "The annual permitted rent increase published on June 1 with effect from June 30"],
      ],
    }),
  ];
}

module.exports = { chapter10, chapter11, chapter12 };
