// plan_content_b.js — Chapters 4-6
const { h1, h2, h3, p, rich, bullet, tbl } = require("./plan_lib");

function chapter4() {
  return [
    h1("4. System Scope: Actors, Modules and Functional Baseline"),
    p("This chapter fixes the functional scope of the platform so that the roadmap in Chapter 5 has an unambiguous object. The scope is expressed three ways: the actors who interact with the system, the thirteen functional modules they touch, and the exclusions that keep the platform inside its legal mandate. Nothing new is introduced here; the chapter consolidates what was already agreed in the requirements and use-case stages and aligns it with the directive."),
    h2("4.1 Actors"),
    ...tbl({
      caption: "System actors and their primary interests",
      headers: ["Actor", "Tier", "Primary interest", "Representative use cases"],
      widths: [20, 16, 36, 28],
      zebra: true,
      rows: [
        ["Landlord (Akeray)", "Public", "Register properties and contracts, receive payments through legal channels, obtain incentives lawfully", "Onboarding, contract creation, amendment, increase application"],
        ["Tenant (Tekeray)", "Public", "Verify a contract is registered, pay electronically, complain safely", "Contract verification, e-payment, complaint submission"],
        ["Agent / proxy", "Public", "Act for a party with legal proxy and identification", "Registration by proxy, witness attestation"],
        ["Woreda registrar / officer", "Woreda office", "Verify, certify, stamp, number and record contracts; validate increases; receive complaints", "Nine-point verification, certification, correction, complaint intake"],
        ["Sub-city monitor", "Sub-city office", "Track woreda performance, aggregate data, escalate issues", "Monitoring dashboard, data consolidation"],
        ["Bureau analyst / head", "City Bureau", "Run the adjustment study, publish rates, amend the model contract, direct enforcement", "Rate computation and publication, model contract versioning, penalty referral"],
        ["Committee and Ministry roles", "City and federal", "Hear appeals, grant final administrative decisions, consume national statistics", "Appeal hearing, national publication"],
      ],
    }),
    h2("4.2 The Thirteen Modules"),
    p("The modules below are the stable functional decomposition used by the roadmap. Each names its principal legal basis and the additions the directive brings. Sprints in Phase 4 are built directly from this table."),
    ...tbl({
      caption: "Module baseline with legal basis and directive additions",
      headers: ["Module", "Purpose", "Principal legal basis", "Directive-driven additions"],
      widths: [22, 30, 22, 26],
      zebra: true,
      rows: [
        ["M1 Party registration and identity", "Landlord, tenant and agent onboarding; identity capture and verification", "Proclamation Arts. 4, 7", "Accepted identification list with original-and-copy rule; proxy and two-witness documents; deaf-party accessibility data"],
        ["M2 Property registry and status", "Property records with status classification and exemption clocks", "Proclamation Arts. 2, 10", "Ownership evidence types: holding certificate, confirmation for undocumented holdings, court-sale documents, inheritance transfer"],
        ["M3 Model contract studio", "Digitized model agreement with versioning", "Proclamation Art. 5; Directive Art. 4", "Bureau amends and distributes the template; office copy rule; contract content checklist including service-fee allocation"],
        ["M4 Registration and certification workflow", "End-to-end woreda workflow from presentation to certified contract", "Proclamation Arts. 4, 7; Directive Arts. 6 to 9", "Nine-point checklist; registrar certification acts including interpreter flow; stamping desk; numbering; registry book and database entry; legacy annotation"],
        ["M5 Rent ceiling and annual adjustment engine", "Ceiling computation, exemption windows, adjustment calendar", "Proclamation Arts. 8 to 11; Directive Art. 11", "June 1 publication and June 30 effect automation; pre-effect amendment registration check; Bureau study workspace"],
        ["M6 Electronic payment ledger", "Bank and e-payment recording with receipts", "Proclamation Arts. 12 to 14; Directive Art. 16(4)", "Payment-method confirmation duty at woreda; cash-payment flags feeding the ten-percent fine referral"],
        ["M7 Compliance monitoring and control", "Own-initiative and complaint-based control by teams", "Proclamation Art. 20; Directive Art. 20", "Team control with identification; vacancy monitoring beyond six months; vacancy tax band computation for referral"],
        ["M8 Complaint, appeal and dispute management", "Intake, investigation, decisions, committee appeals, court escalation", "Proclamation Arts. 20 to 26; Directive Arts. 17 to 19", "Eight grounds checklist; multichannel intake including verbal and telephone; completeness verification; complaint register"],
        ["M9 Penalty and enforcement", "Administrative fines and referrals", "Proclamation Arts. 4, 29 to 32; Directive Art. 22", "Configurable fine ladder; vacancy surcharge bands five to twenty-five percent; referral to tax and enforcement bodies; court-recovery tracking"],
        ["M10 Data management, replication and backup", "Custody, scanning, tier-wise replication and recovery", "Directive Art. 13", "Uniform numbered registry book; hard and soft dual custody; woreda to sub-city to Bureau replication with upward change propagation"],
        ["M11 Reporting, dashboards and national publication", "Tier analytics and public data publication", "Proclamation Art. 18", "Sub-city aggregation duty; Bureau city analytics; Ministry national publication feed"],
        ["M12 Notification and deadline engine", "All statutory clocks with reminders and escalations", "Proclamation Arts. 6, 7, 8, 25, 26; Directive Arts. 10, 19", "Thirty-day amendment registration window; complaint decision window; appeal windows; June calendar events"],
        ["M13 System administration and configuration", "Org hierarchy, roles, per-city rule sets, forms", "Directive Arts. 2, 14", "Per-city configuration sets; model contract versions; penalty parameters; identification-type catalogues"],
      ],
    }),
    h2("4.3 Exclusions"),
    p("In line with Article 3(3) of the proclamation, the platform excludes hotels, resorts, guest houses and commercially licensed rental operations, and it does not administer houses used for purposes other than residence. Where such cases surface during operation, the system records and routes them to the competent bodies rather than processing them as residential rent cases. Keeping these exclusions explicit prevents scope drift during construction and protects the legal defensibility of every automated decision the platform makes."),
  ];
}

function chapter5() {
  return [
    h1("5. Phase-Gated Implementation Roadmap"),
    p("The roadmap is expressed as nine phases. For each phase this chapter states the objective, the key activities, the deliverables, and the exit criteria that the corresponding gate tests. Durations are deliberately indicative and will be fixed in the Phase 0 schedule baseline, because a schedule written before the charter is approved would be a guess dressed as a plan."),
    h2("5.1 Phase 0: Initiation and Governance"),
    p("Objective: establish the project on firm administrative ground so that every later artifact has an owner, a baseline, and an approval path."),
    bullet("Confirm the three legal instruments as the binding baseline, and obtain the official Amharic texts for verification of any figure that the scanned copies leave ambiguous."),
    bullet("Appoint the project owner and product owner, name stakeholder representatives for the Ministry, the Bureau, the sub-city and woreda offices, and the information technology department."),
    bullet("Approve this implementation plan and the project charter, including scope, exclusions, and the gate calendar."),
    bullet("Stand up the collaboration workspace, repositories, and the decision register."),
    p("Deliverables: project charter v1.0, stakeholder map, approved implementation plan, decision register. Gate G0 exits when the charter and this plan are signed and the ambiguity list for Phase 1 verification is agreed."),
    h2("5.2 Phase 1: Requirements Consolidation and Legal Traceability"),
    p("Objective: turn the three instruments and all prior analysis into one approved SRS in which every requirement is traceable to a legal source and forward to a test."),
    bullet("Reconcile the proclamation, the directive and the model agreement into the requirement set, upgrading the earlier thirteen-module baseline with the directive rules listed in Chapter 2."),
    bullet("Resolve the flagged ambiguities, notably the fine ladder of Directive Article 22, against the official text, and record each resolution in the decision register."),
    bullet("Build the bilingual English and Amharic terminology glossary so that interface labels, forms and notices use the directive's own words."),
    bullet("Produce SRS v1.0 conforming to ISO/IEC/IEEE 29148, with the traceability matrix covering article, requirement, module, use case and future test identifier."),
    p("Deliverables: SRS v1.0, traceability matrix v1.0, glossary, resolved-parameter log. Gate G1 exits when the SRS and the matrix are approved and no requirement is without a legal source."),
    h2("5.3 Phase 2: System and Software Design"),
    p("Objective: design a platform that implements the SRS and survives government operation: multi-tier, auditable, bilingual and configurable."),
    bullet("High-level design: web portal for the public, registrar workbench for woreda offices, monitoring consoles for sub-city and Bureau, and Ministry analytics; an application service layer; and integration services for bank and electronic payment, identification verification, and SMS or notification channels."),
    bullet("Database design covering parties, properties, contracts and versions, registrations, payments, complaints, appeals, penalties, referrals, organizational hierarchy, configuration sets and the immutable audit log."),
    bullet("Security design: role-based access mapped to tier and office, encryption, session policy, and audit of every registration, correction and decision as required by Directive Articles 12 and 13."),
    bullet("Interface design: bilingual wireframes for each workflow, checked against the model agreement's field list and the nine-point checklist screens."),
    p("Deliverables: architecture specification, database design, security and threat model, wireframe pack, interface specification. Gate G2 exits when designs are approved and every SRS requirement maps to at least one design element."),
    h2("5.4 Phase 3: Environments and Seed Configuration"),
    p("Objective: prepare the runtime landscape and seed the configuration the platform needs to behave like the directive on day one."),
    bullet("Provision development, staging and production environments with the backup scheme of Directive Article 13 at each tier."),
    bullet("Build the continuous integration and delivery pipelines: automated build, unit tests, static analysis, and staged promotion with release tagging."),
    bullet("Seed configuration: organizational tree for Addis Ababa with its sub-cities and woredas, roles, identification catalogues, property status types, model contract v1, penalty parameters from the resolved ladder, and the June adjustment calendar."),
    p("Deliverables: environment inventory, pipeline documentation, seeded configuration. Gate G3 exits when a walkthrough shows a staged promotion running end to end and the seeded hierarchy matching the official structure."),
    h2("5.5 Phase 4: Incremental Module Construction"),
    p("Objective: build the thirteen modules in seven sprints, each ending in a working increment demonstrated to the project owner."),
    ...tbl({
      caption: "Sprint plan mapped to modules",
      headers: ["Sprint", "Modules", "Increment highlights"],
      widths: [12, 22, 66],
      zebra: true,
      rows: [
        ["S1", "M13, M1", "Organization hierarchy and roles; party onboarding with identification and proxy handling"],
        ["S2", "M2, M3", "Property registry with status and exemption clocks; model contract studio with version control"],
        ["S3", "M4", "Registration and certification workflow: checklist, registrar acts, interpreter flow, stamping desk, numbering, registry book, database entry, legacy annotation"],
        ["S4", "M5, M6", "Adjustment engine with June calendar and increase validation; payment ledger with electronic-method enforcement and cash flagging"],
        ["S5", "M8, M12", "Complaint intake with grounds checklist and register; dispute pipeline with appeal and court clocks; deadline engine"],
        ["S6", "M7, M9", "Control-team workflows; vacancy monitoring; penalty ladder computation, referrals and court-recovery tracking"],
        ["S7", "M10, M11", "Replication and backup at tier level; dashboards, aggregation and national publication feed"],
      ],
    }),
    p("Each sprint runs unit tests to the agreed coverage, closes its slice of the traceability matrix, and is reviewed in a short demonstration. Defects found in review are fixed before the next sprint starts. Gate G4 exits when all seven increments are demonstrated, the platform is functionally complete against the SRS, and no severity-one or severity-two defects remain open."),
    h2("5.6 Phase 5: Integration, Security and Compliance Testing"),
    p("Objective: prove the assembled system against integrations, load, attack, and above all the law."),
    bullet("Integration testing with the bank and payment sandbox and the identification service, including failure and timeout behaviour."),
    bullet("System and regression testing across all modules; performance testing at projected woreda workload with headroom for city-wide peaks."),
    bullet("Security testing against the agreed OWASP ASVS level, including access control between tiers and audit-trail integrity."),
    bullet("Execution of the legal compliance test matrix: every traced article exercised by at least one named test case, with the matrix attached to the test report."),
    p("Deliverables: test plan, level-wise test reports, compliance matrix with results, security assessment. Gate G5 exits when all critical tests pass and the compliance matrix shows no failed legal rule."),
    h2("5.7 Phase 6: User Acceptance and Legal Validation"),
    p("Objective: let the real roles judge the system, using scripts derived from the use cases, and let the legal side certify that automated behaviour matches the directive."),
    bullet("Role-based UAT: registrars run real registration files through the checklist; Bureau analysts run the adjustment publication flow; complaint officers run intake to decision; committee members hear a rehearsed appeal."),
    bullet("Legal validation session: article-by-article walkthrough of the compliance matrix with the Bureau's legal experts, recording every deviation and its resolution."),
    bullet("Defect triage with severity definitions and agreed fix schedule; re-test of fixed items."),
    p("Deliverables: UAT scripts and results, legal validation memorandum, defect log with closure status. Gate G6 exits on a signed UAT certificate and a legal memorandum with no unresolved deviation."),
    h2("5.8 Phase 7: Data Migration, Training and Pilot"),
    p("Objective: bring legacy reality into the platform and prove operation in live woredas before city-wide exposure."),
    bullet("Migrate legacy contracts: create party and property records, apply the legacy annotation of Directive Article 8(2), scan and attach documents, and reconcile counts against the registry books as Article 13 requires."),
    bullet("Train by role and tier: registrar front-desk practice, sub-city monitoring, Bureau analytics and rate publication, and system administration."),
    bullet("Run the pilot in agreed woredas with daily support, measuring registration cycle time, checklist compliance and replication correctness."),
    bullet("Produce public awareness material as Article 14 and Article 16 require, so citizens know what a valid contract looks like."),
    p("Deliverables: migration report with reconciliation, training attendance and competence records, pilot exit report. Gate G7 exits when the pilot woredas operate without severity-one issues and reconciliation balances."),
    h2("5.9 Phase 8: Go-Live, Operations and Continuous Improvement"),
    p("Objective: roll out in waves, stabilize, and hand over to a governed operation that can run the annual cycle unaided."),
    bullet("Wave rollout from pilot woredas to all woredas of the pilot sub-city, then city-wide, then preparation for replication to other cities as configuration sets."),
    bullet("Hypercare support with agreed service levels, then transition to standard operations with the operations manual and runbook."),
    bullet("Operate the annual adjustment cycle end to end: study workspace, June 1 publication, June 30 effect, amendment wave, and compliance follow-up."),
    bullet("Operate penalty referrals and court-recovery tracking with the competent bodies, and publish national data to the Ministry."),
    bullet("Post-implementation review at ninety days feeding the continuous improvement backlog."),
    p("Deliverables: go-live checklist execution, operations manual, service reports, ninety-day review. Gate G8 approves go-live; Gate G9 closes the project on the ninety-day review with lessons recorded."),
  ];
}

function chapter6() {
  return [
    h1("6. Interaction and Governance Model"),
    p("Smooth interaction is engineered, not hoped for. The mechanism has four parts: stage gates that concentrate decisions at phase boundaries, a fixed working cadence between gates, a decision register that records every choice with its rationale, and a change-control rule that keeps scope honest. The table below is the contract between the project owner and the delivery team; if the owner can answer the questions at each gate, the project cannot drift."),
    ...tbl({
      caption: "Stage gates: what the project owner reviews and approves",
      headers: ["Gate", "When", "You review", "You approve or decide"],
      widths: [8, 20, 40, 32],
      zebra: true,
      rows: [
        ["G0", "End of Phase 0", "Charter, this plan, stakeholder map, ambiguity list", "Approve baseline; confirm official texts to be obtained"],
        ["G1", "End of Phase 1", "SRS v1.0 with one-page summary; resolved ambiguities; glossary", "Approve requirements; sign parameter resolutions"],
        ["G2", "End of Phase 2", "Architecture, database and security design; wireframes", "Approve designs; prioritize any wireframe changes"],
        ["G3", "End of Phase 3", "Environments walkthrough; seeded hierarchy and rules", "Accept environments; confirm configuration values"],
        ["G4", "After each sprint and at sprint 7", "Increment demo against use cases; sprint test summary", "Accept increment; reprioritize backlog if needed"],
        ["G5", "End of Phase 5", "Test reports; compliance matrix; security assessment", "Accept test evidence; authorize UAT start"],
        ["G6", "End of Phase 6", "UAT results; legal validation memorandum; defect log", "Sign UAT certificate; authorize migration and pilot"],
        ["G7", "End of Phase 7", "Migration reconciliation; training records; pilot report", "Select go-live waves; confirm readiness"],
        ["G8", "Start of Phase 8", "Cutover checklist; rollback plan; support arrangements", "Give go-live order"],
        ["G9", "Ninety days after go-live", "Operations reports; ninety-day review; improvement backlog", "Close project or direct follow-on work"],
      ],
    }),
    p("Between gates, the cadence is fixed. Sprint demonstrations occur at each sprint end with a written summary of what changed. Any question that would alter scope, cost or a legal parameter is logged as a decision request rather than resolved informally, and the register records who decided, what was decided, and why. Weekly written status is short and factual: activities done, activities next, risks moved, decisions pending. This rhythm keeps the owner informed without drowning the project in meetings."),
    p("Change control is deliberately simple. Any change request receives a one-page impact assessment covering effort, schedule, legal effect and risk; the owner approves or rejects it at the next gate or, if urgent, by written circulation. Nothing enters the build without a register entry. Experience shows that this single discipline prevents most disputes, because the cost of every good idea is made visible before it is adopted rather than after."),
  ];
}

module.exports = { chapter4, chapter5, chapter6 };
